### PR TITLE
HA queues and version bump

### PR DESCRIPTION
**Pull request by cap10morgan**
This implements the HA queues policy in [this card](https://www.pivotaltracker.com/story/show/95494098) and bumps the version of RabbitMQ to 3.5.3 as [specified in this card](https://www.pivotaltracker.com/story/show/92521312). Since we need to deploy the former anyway, it made sense to bring the latter along for the ride.

I've disabled auto-deploys of RabbitMQ for now because they don't seem to reliably work yet (something with the Consul autoclustering plugin isn't working correctly when pulling nodes and then trying to re-join the cluster).

But it can be deployed manually, so I'll just do that carefully once this is LGTM'd.

### CODE REVIEW

**Comment by cap10morgan** [comment]
This is deployed to the staging CoreOS cluster. I created a new queue on there using the Rabbit management app and it had the policy "ha-all" applied to it automatically.

**Comment by bwreid** [comment]
Is there a way to test this other than confirming that staging is up?

**Comment by cap10morgan** [comment]
You can [go here](http://10.36.116.61:15672/) and confirm that a) it's up and b) creating a new queue gets the "ha-all" policy applied to it.

Anything deeper than that would involve creating a few queues and then destroying and restarting rabbit nodes one at a time on staging and confirming that the queues live on. Which could be fun?

Unfortunately right now getting a rabbit node back into an existing cluster is annoyingly manual and tedious due to a Consul autocluster plugin bug that I'm still working through w/ the upstream author. But I'd be happy to sit down and do the above w/ you if you want to test it at that level.

**Comment by bwreid** [comment]
Cool, I can confirm the former.

For the latter, it sounds like you'll be hitting this soon enough so I'm fine just LGTM-ing this as long as it's not forgotten.

**Pull request merged**
